name: Sentinel Unit Tests

on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'

# on:
#   pull_request:

permissions: read-all

jobs:
  test:
    name: Test Sentinel Policies
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sentinel-version: [0.22.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Sentinel
        run: |
          wget --no-verbose --timestamping -O sentinel.zip https://releases.hashicorp.com/sentinel/${{ matrix.sentinel-version }}/sentinel_${{ matrix.sentinel-version }}_linux_amd64.zip
          mkdir tmp
          pushd tmp
          unzip "../sentinel.zip"
          chmod +x sentinel
          mv ./sentinel ../sentinel-cli
          popd
          rmdir tmp
          rm sentinel.zip

      - name: Sentinel Tests
        run: |
          ./sentinel-cli test -verbose ./sentinel/policies/aws/
